### ISSUE TITLE
theCreative TV

### ISSUE THREAD

**Issue by sirgawain0x** [livepeer/grants#96]
**Give a 3 sentence description for your proposal.**

[Creative Org DAO, LLC.](https://creativeplatform.xyz) Is building an NFT-gated VoD platform (CreativeTV) with LivePeer for creators to earn from their art through brand partners marketing their digital products. CreativeTV will be community-governed using Snapshot, empowering fans to curate the content they want to see and control what the platform will become. Web3 educational videos will always be free and publicly available to cultivate the movement, developing a self-sustaining ecosystem allowing creatives to read-write-own art.

**Describe the problem you are solving.** 

Creatives aren't earning their fair share from centralized content platforms like YouTube, TikTok, Instagram, etc., with revenue mainly generated from ads curated by those platforms. They also don't often own the art published and have to surf an algorithm that rewards over saturation, forcing creatives to search for alternate ways to support their work. This environment impacts fans searching for content through an uncontrolled noise funnel without tangible incentives.

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 

To solve these problems, we are building a platform that integrates with Livepeer to create and distribute video IP 100% owned by creatives to help them generate revenue. Creatives will use their content to become broadcasters with ads, concerts, and other art curated and governed within the community. This solution, in turn, develops an ecosystem nourished by fan engagement with P2E models and cryptoeconomic incentives that brands can utilize to market products. 

**Describe why you are the right team with the capability to build this.**

We aim to push the limits of LivePeer's protocols by using various SDKs to develop tokens for creators with large audiences to expand their community. This will help curate new emerging content production channels and create unique creator ecosystems, which will help push adoption and grow LivePeer.

**Describe the scope of the project, including a 3-month timeline and milestones.** 

We are a focused, international, 6-person team developing professionally for over 13 years, with two years consistently adding value to web3 ecosystems like POAP, Snapshot, Chainlink, Rarible marketplace, and others. We have the skill sets to effectively complete this project in a user-friendly and eye-catching way. 

**Members** 
-  [G2  founder/dev lead](https://github.com/gawainb)
-  [headishere  project manager](https://github.com/cakeee) 
-  [dev_ninja senior frontend developer](https://github.com/starhelios)
-  [agreene solidity developer](https://github.com/greenealexander) 

1-Month Milestone Complete Backend Integration:
- Livepeer - Tableland integration 
- LivePeer Asset creation 
- Write and deploy ERC-721 access NFT to token gate the video platform
- Conduct Unit & Integration Testing

2-Month Milestone Design and Implement UI: 
- Start UI mockup Design
- Connecting the frontend UI codebase to the SDKs (Livepeer, Tableland), backend server, and smart contract
- Validate UI/UX 
- Create of UAT test plan/cases. Identify Test Scenarios.

3-Month Milestone Testing, Security and Release: 
- Perform UAT testing, Use Results to fix bugs and make adjustments
- Penetration Testing / Bounty Reviews
- Prepare production release marketing 
- Release 

Long-term, our DAO would also like to support our own LivePeer transcoding node and assist in implementing Livepeer with our Metaverse partner [Stageverse](https://stageverse.com).

**Success Measurements**

- [x] `Onboard 5 independent creators with at least 2 pieces of video content each by end of Q1 2023`

- [x] `Create 2 Brand Partnerships that we can use to advertise digital products by end of Q1 2023`

- [x] `Integration into Stageverse (Metaverse) SDK by Q2 2023`

**Please estimate hours spent on the project based on the above and how much funding you will need.** 

-  Core team hours 40 hrs/week (team of 6) $35,000
-  Smart Contract Auditing $5,000
- Marketing $5,000
-  Video mining node and operations  $5,000

**Comment by shann7** [comment]
Thanks for this proposal! We are reviewing and will get back to you asap

**Comment by gawainb** [comment]
> Thanks for this proposal! We are reviewing and will get back to you asap

Circling back around as we would like to request a smaller amount of 10K for our grant. We are just about complete with platform using Livepeer and Lens.

**Comment by hansy** [comment]
@sirgawain0x Thanks for your patience! We'd love to further explore your idea. In particular, we're very interested in learning more about your plans for incorporating a DAO around your application, your Tableland and metaverse integrations, as well as any plans for running your own Livepeer node.

Are you available for a scoping call? I'm hansy#9576 on Discord. Can coordinate further through there.

**Comment by sirgawain0x** [comment]
Hello @hansy I apologize for not seeing this. 

We have been building our video streaming platform while we were waiting to hear back an update 🙈

We would really like to connect and explore our project build further. 

See you in Discord!

**Comment by sirgawain0x** [comment]
Just want to post our latest updates on our build: 

https://tv.creativeplatform.xyz

**Comment by hansy** [comment]
Hey @sirgawain0x! Good to see you here. So it seems like you want to pair back the grant amount to $10k? I'd love to know what you'd like to use the money for, in particular what milestones you'd like to reach within your app as well as a timeline for those milestones.

**Comment by sirgawain0x** [comment]
Dear @hansy, thank you for getting back to us.

We have a clear plan for the development of Creative TV, which includes the following features:

- Enabling creators to issue "Lootbox" non-fungible tokens (NFTs) or Proof of Attendance Protocol (POAP) tokens to their viewers.
- Implementing the ability for viewers to tip creators using their own social token ([meTokens](https://metokens.com)).
- Furthering token-based access through our decentralized autonomous organization (DAO) and integrating the ability to curate videos and content through our Moloch DAO platform.
- Integrating Superfluid to facilitate micro transactions for a creator's social token (meToken), enabling us to establish streaming royalties based on platform revenue.

To accomplish these goals, we are requesting $10,000 in funding. The funds will be allocated as follows:

- Core team hours 40 hrs/week (team of 2) $5,000
- Video Mining Node Development $2,000
- Admin & Operations $1,000
- Marketing $2,000

We estimate that the project will take between 2 to 3 months to complete. Thank you for considering our proposal.

**Comment by hansy** [comment]
@sirgawain0x Great! Can you break this up into milestones (probably 3 - one for each month of development) and a deliverable for each milestone?

**Comment by hansy** [comment]
@sirgawain0x Do you have time this week for a chat about your application? I'm hansy#9576 on Discord.

**Comment by sirgawain0x** [comment]
@hansy I do. Here is my calendar to select some time to connect: https://cal.com/thecreative/secret

**Comment by sirgawain0x** [comment]
Hello @hansy,

Here are our deliverables per our Discord conversation. 

Month 1:

- [ ] Token-based access system set up and tested
- [ ] Integration of Moloch DAO platform completed and tested
- [ ] Functionality for viewers to tip creators using their own social token (meToken) developed and tested
- [ ] Superfluid integration started and progress documented

Month 2:

- [ ] Superfluid integration completed and tested
- [ ] Streaming royalties based on revenue of the platform enabled and tested
- [ ] "Lootbox" NFTs or POAP tokens enabled and tested
- [ ] Core video mining node developed and tested

Month 3:

- [ ] All features and functionalities tested and finalized
- [ ] Marketing and outreach plan created and initiated
- [ ] Operations and administration plan created and initiated
- [ ] Platform fully operational and running smoothly

These deliverables can be verified via: 
[Github](https://github.com/creativeplatform/monorepo)
[Production](https://tv.creativeplatform.xyz)

**Comment by hansy** [comment]
Milestones 1 and 2 look good. It's still unclear what the deliverable for Milestone 3 is. Instead, maybe we can turn that into a success bonus. So:

## Milestone 1
**Amount**: $3k
**Duration**: 1 month

- Token-based access system set up and tested
- Integration of Moloch DAO platform completed and tested
- Functionality for viewers to tip creators using their own social token (meToken) developed and tested
- Superfluid integration started and progress documented

## Milestone 2
**Amount**: $3k
**Duration**: 1 month

- Superfluid integration completed and tested
- Streaming royalties based on revenue of the platform enabled and tested
- "Lootbox" NFTs or POAP tokens enabled and tested
- Core video mining node developed and tested

## Success Bonus
**Amount**: $4k
**Duration**: n/a

- 50 videos uploaded from creators
- 1000 minutes watched


We can play around with the Success Bonus numbers, but effectively the idea is to come up with lofty, but achievable numbers for your project. We don't often put a timeline on the success bonus, so hopefully that should be low stress.

**Comment by sirgawain0x** [comment]
@hansy awesome, this works well for us. We will get started on the first milestones top of the week.

**Comment by hansy** [comment]
We'd like to to fund this application! To kickstart the grant, we'll send you 20% upfront payment, and then graduate the rest of the milestone payments to you upon review and completion. 

The success bonus/metric must be met by the end of the grant period to receive the amount.

If this works for you, send me an arbitrum-compatible wallet address where I can send the LPT to. Upon initial payment confirmation, the grant will officially begin and I will add the official grant schedule (milestone due dates) here.

**Comment by hansy** [comment]
Forgot to post the tx hash here along with the schedule! Here's the tx receipt for the upfront payment: https://arbiscan.io/tx/0x0a098b1c9dc6a1e4b10457ffde9d57f716f2cb5d8b2cda8edfa2e9a0fa136cd0

Milestone schedule:

Milestone 1 - June 29
Milestone 2 - July 29
Success metric - July 29

Let me know if you have any questions!

**Comment by hansy** [comment]
Here's the tx receipt for Milestone 1: https://arbiscan.io/tx/0xf472c34c2481775f637cd1c7281b2665fbde37e91de7941f1685f3cf094315a8!

**Comment by sirgawain0x** [comment]
Currently, working on code refactoring and purchasing Livepeer video NFTs via meTokens.

**Comment by sirgawain0x** [comment]
Gm, @hansy bot closed me out 🙁 I had to purchase a NVIDIA GPU, but I'm just about finished up with setting up the Orchestrator node.

**Comment by sirgawain0x** [comment]
Hello @hansy we are wrapping up our final updates and will be completed by the weekend to submit Monday, December 18th.

**Comment by sirgawain0x** [comment]
@hansy We have our Livepeer Orchestrator running but looks like we need a minimum of 46 LPT in order to register we only have 17 LPT left. 
![Screenshot 2023-12-13 164918](https://github.com/livepeer/grants/assets/1490181/807fb1c0-3266-4298-a89c-3338e3ce9421)
![Screenshot 2023-12-13 165217](https://github.com/livepeer/grants/assets/1490181/9e3502fa-6ce5-4f4b-9a8d-61c583ad1f36)

We are testing the other milestone features to make sure those are functioning to satisfy our remaining milestones.

**Comment by sirgawain0x** [comment]
Hello @hansy just wanted to see if we can connect on our latest milestone completions this week. Here is my calendar to grab some time: https://cal.com/thecreative/secret-30

**Comment by sirgawain0x** [comment]
Gm @hansy I haven't given up, instead of doing workarounds and shortcuts we waited on our infrastructure partner Superfluid to release  their GDA contract so that we can effectively tackle royalties and advertising. That is n JJ https://docs.superfluid.finance/docs/concepts/overview/distributions

Lastly, finding qualified developers to collaborate with has been a challenge. Nonetheless, I'll have an updated demo to submit soon.

**Comment by hansy** [comment]
Awesome. Love the hustle and persistence. We'll be around.
